name: Assign
on:
  issues:
    types: [opened]
jobs:
  assignMonaLisa:
    name: Assign CanhTV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Assign CanhTV
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: assign @canhtv-0838