name: Build  before merging

on:
  pull_request:
    types: [opened, edited, reopened, closed, merged]

jobs:
  build_before_merging:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run tests
        run: ./gradlew test

      - name: Build project
        run: ./gradlew assemble

      - name: Open Pull Requests Chatwork Notifier
        uses: KeisukeKudo/open_pull-request_chatwork_notifier@v1
        with:
          chatwork-api-token: ${{ secrets.CHATWORK_API_TOKEN }}
          chatwork-room-id: ${{ secrets.CHATWORK_ROOM_ID }}