name: Comment
on:
  issues:
    types: [opened]
  jobs:
    assignCanh:
      name: Comment on issue
      runs-on: ubuntu-16.04
      steps:
        - uses: actions/checkout@master
        - name: Label issue
          uses: actions/github@v1.0.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            args: comment "Thank you for openning an issue, Canh will take care of it"