name: Greet First Time Contributors

on: [pull_request, issues]

jobs:
  greet_first_contribution_job:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thank you for helping us make this project better 🙂'
          pr-message: 'Thank you for submitting your first PR 🎉'
